= AspectJ 1.9.9
:doctype: book
:leveloffset: +1

= AspectJ 1.9.9.1

_© Copyright 2022 Contributors. All rights reserved._

_Release info: 1.9.9.1 available 31-Mar-2022_

Bugfix release for some compiler options related to the Java Platform Module System (JPMS) which were not working, most
importantly `--add-modules`, `--add-exports` and `--add-reads`. See
https://github.com/eclipse-aspectj/aspectj/issues/145[issue #145].

This probably was broken for a long time. AspectJ still is not boasting extensive JPMS support or test coverage, but
this improvement seems substantial enough to justify a minor release, instead of keeping users waiting for the next
regular release.

= AspectJ 1.9.9

_© Copyright 2022 Contributors. All rights reserved._

_Release info: 1.9.9 available 24-Mar-2022_

Please note that Bugzilla for issue management is deprecated and new issues should be filed as
https://github.com/eclipse-aspectj/aspectj/issues/new[GitHub issues]. The list of issues addressed for 1.9.9 can be found
here:

* https://github.com/eclipse-aspectj/aspectj/issues?q=is%3Aissue+is%3Aclosed++milestone%3A1.9.9[GitHub 1.9.9]
* https://github.com/eclipse-aspectj/aspectj/issues?q=is%3Aissue+is%3Aclosed++milestone%3A1.9.9.1[GitHub 1.9.9.1]
* https://bugs.eclipse.org/bugs/buglist.cgi?bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&f0=OP&f1=OP&f3=CP&f4=CP&j1=OR&list_id=16866879&product=AspectJ&query_format=advanced&target_milestone=1.9.9[Bugzilla 1.9.9]

== New features

AspectJ 1.9.9 supports https://openjdk.java.net/projects/jdk/18/[Java 18] and its final and preview features, such as:

* Pattern matching for `switch` (preview 2)

== Improvements

In annotation style aspects, asynchronous `proceed()` calls in `@Around` advice now works in threads created from within
the advice. Previously, this was only working in native syntax aspects. There is still a limitation with regard to
asynchronous proceed, if you do not create the thread in the advice but want to use e.g. an `ExecutorService` with its
own thread pool. This still is not working in annotation style aspects, only in native syntax ones.

See https://github.com/eclipse-aspectj/aspectj/issues/128[issue #128] and
https://github.com/eclipse-aspectj/aspectj/pull/132[pull request #132] for more details.

== Code examples

You can find some sample code in the AspectJ test suite under the respective AspectJ version in which the features were
first supported (possibly as JVM preview features):

* https://github.com/eclipse-aspectj/aspectj/tree/master/tests/features198/java17[Pattern matching for switch, preview 1]
* https://github.com/eclipse-aspectj/aspectj/tree/master/tests/features199/java18[Pattern matching for switch, preview 2]
* https://github.com/eclipse-aspectj/aspectj/tree/master/tests/bugs199/github_128[Asynchronous proceed in native vs.
  annotation style syntax]

== Other changes and bug fixes

* Fix a bug which led to ``NullPointerException``s, if too many JAR archives were on the classpath. Too many here means
  the value of system property `org.aspectj.weaver.openarchives` (1,000 by default). The AspectJ compiler is meant to
  close archives upon cache exhaustion and then re-open them, if it needs them again later. Re-opening was broken, but
  now the compiler works reliably even for cache sizes as small as 20. See
  https://github.com/eclipse-aspectj/aspectj/issues/125[issue #125].
* Improvements for `if()` pointcuts in annotation syntax, see issues
  https://github.com/eclipse-aspectj/aspectj/issues/115[#115], https://github.com/eclipse-aspectj/aspectj/issues/120[#120],
  https://github.com/eclipse-aspectj/aspectj/issues/122[#122].
* Thanks to Andrey Turbanov for several clean code contributions.

== AspectJ usage hints

=== AspectJ compiler build system requirements

Since 1.9.8, the AspectJ compiler `ajc` (contained in the `aspectjtools` library) no longer works on JDKs 8 to 10. The
minimum compile-time requirement is now JDK 11 due to upstream changes in the Eclipse Java Compiler (subset of JDT
Core), which AspectJ is a fork of. You can still compile to legacy target versions as low as Java 1.3 when compiling
plain Java code or using plain Java ITD constructs which do not require the AspectJ runtime `aspectjrt`, but the
compiler itself needs JDK 11+. Just like in previous AspectJ versions, both the runtime `aspectjrt` and the load-time
weaver `aspectjweaver` still only require JRE 8+.

=== Use LTW on Java 16+

Please note that if you want to use load-time weaving on Java 16+, the weaving agent collides with
https://openjdk.java.net/jeps/396[JEP 396 (Strongly Encapsulate JDK Internals by Default)]. Therefore, you need to set
the JVM parameter `--add-opens java.base/java.lang=ALL-UNNAMED` in order to enable aspect weaving. This is due to the
fact that the weaver uses internal APIs for which we have not found an adequate replacement yet when defining classes
in different classloaders.

=== Compile with Java preview features

For features marked as preview on a given JDK, you need to compile with `ajc --enable-preview` and run with
`java --enable-preview` on that JDK.

Please note, that you cannot run code compiled with preview features on any other JDK than the one used for compilation.
For example, records compiled with preview on JDK 15 cannot be used on JDK 16 without recompilation. This is a JVM
limitation unrelated to AspectJ. Also, e.g. sealed classes are preview-1 on JDK 15 and preview-2 on JDK 16. You still
need to recompile, no matter what.
