= AspectJ 5 v1.5.1 Readme

_© Copyright 2006 Contributors. All rights reserved._

This release is primarily a bug fix and performance / memory usage
release. Over 70 fixes and enhancements have been incorporated since
1.5.0, you can see the list through
https://bugs.eclipse.org/bugs/buglist.cgi?query_format=advanced&product=AspectJ&target_milestone=1.5.1&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED[this
bugzilla query].

AspectJ 1.5.1 has significantly lower memory usage than AspectJ 1.5.0,
especially when building inside of AJDT. The improvements are also
noticeable when batch building with Ant, or when load-time weaving.
Batch building a project with over 1000 source files with both AspectJ
1.5.1 and AspectJ 1.5.0 shows a 16% reduction in peak memory usage, and
an 8% reduction in heap consumed by temporary objects. The AspectJ 1.5.1
compiler integrated into AJDT gives memory savings of at least 50%. The
greater savings in the AJDT environment are due to improvements in areas
such as structure model generation that are not exercised

For information on bug fixes in AspectJ 5 v1.5.1, see the
link:changes.html[changes] document.
