= AspectJ 5 v1.5.2 Readme

_© Copyright 2006 Contributors. All rights reserved._

This release is primarily a bug fix release. It includes approximately
60 fixes and enhancements that have been incorporated since the 1.5.1
release. You can see the full list through
https://bugs.eclipse.org/bugs/buglist.cgi?query_format=advanced&product=AspectJ&target_milestone=1.5.2&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED[this
bugzilla query].

Notable changes since the 1.5.1 release include:

* https://bugs.eclipse.org/bugs/show_bug.cgi?id=126167[[_126167]] The
handling of proceed in @Around advice has changed to be more compatible
with code style.
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=147711[[_147711]] Members
generated as a result of the AspectJ weaving process are now marked Java
synthetic - enabling coverage tools such as Emma to process woven
classes correctly.
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=138316[[_138316]] AspectJ
has now transitioned from the CPL to the EPL license.
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=140695[[_140695]] Using a
more optimal world for managing types when load-time weaving - reduces
heap usage (work in progress).
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=101983[[_101983]] AspectJ
can now support separate output folders for each input source folder -
enables AJDT to behave more like JDT.

For information on bug fixes in AspectJ 5 v1.5.2, see the
link:changes.html[changes] document.
