= AspectJ 1.9.4

_© Copyright 2019 Contributors. All rights reserved._

The full list of resolved issues in 1.9.4 is available
https://bugs.eclipse.org/bugs/buglist.cgi?bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&f0=OP&f1=OP&f3=CP&f4=CP&j1=OR&list_id=16866879&product=AspectJ&query_format=advanced&target_milestone=1.9.4[here]

_Release info: 1.9.4 available 10-May-2019_

AspectJ 1.9.4 has a couple of important fixes in it:

* Due to the new maven build process being used to build release
artifacts for the first time, there were errors in the _aspectjweaver_ JAR
that affected the ability to use it on the command line as an agent,
this is now fixed.

* A number of users were noticing a `ClassCastException` problem, which I
believe was due to trying to run AspectJ on one level of the JDK whilst
targeting another. This can happen quite easily in Eclipse if running
your Eclipse on Java 8 but developing projects targeting Java 11. The
class cast is because Java8 couldn't understand the packaging of system
classes post Java9 and so couldn't find `java.lang.Object`. This has now
all been tidied up and should work much better. More details in
https://bugs.eclipse.org/bugs/show_bug.cgi?id=546807[546807], thanks to
Denys Khanzhyiev for some tips on getting to the right solution.
