// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package aspectjtest;

privileged aspect ExampleItd {
    declare @field: * MyEntity.myField: -@AnnotationA;
    declare @field: * MyEntity.myField: @AnnotationB;
}
