= The AspectJ^TM^ Development Environment Guide

:doctype: book

_by the AspectJ Team_

_Copyright (c) 1998-2001 Xerox Corporation, 2002 Palo Alto Research Center, Incorporated, 2003-2005 Contributors.
All rights reserved._

This guide describes how to build and deploy AspectJ programs using the AspectJ tools and facilities. See also the
xref:../progguide/progguide.adoc[AspectJ Programming Guide], the documentation available with the AspectJ support
available for various integrated development environments (e.g. https://www.eclipse.org/ajdt/[Eclipse AJDT]), and the
most-recent documentation available from the https://eclipse.org/aspectj[AspectJ project page].

**Table of Contents**

* xref:tools-intro.adoc[Introduction to the AspectJ tools]
* xref:ajc.adoc[`ajc`, the AspectJ compiler/weaver]
* xref:ajdoc.adoc[`ajdoc`, the AspectJ API documentation generator]
* xref:aj.adoc[`aj`, the AspectJ load-time weaving launcher]
* xref:ajbrowser.adoc[AspectJ Browser]
* xref:antsupport.adoc[AspectJ Ant Tasks]
* xref:ltw.adoc[Load-Time Weaving]
* xref:compatibility.adoc[AspectJ version compatibility]
